name: Test e2e


on:
  pull_request:
   types: ["opened", "edited", "synchronized", "labeled", "unlabeled"]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Get PR labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            core.setOutput('labels', labels.join(','));

      - name: Determine if all tests should run
        id: check-all
        run: |
          if [[ "${{ steps.get-labels.outputs.labels }}" == *"run-all"* ]]; then
            echo "Run all tests: true"
            echo "run-all=true" >> $GITHUB_ENV
          else
            echo "Run all tests: false"
            echo "run-all=false" >> $GITHUB_ENV
          fi

      - name: Run e2e tests
        if: ${{ steps.get-labels.outputs.labels != '' }}
        run: |
          echo "Labels from PR: ${{ steps.get-labels.outputs.labels }}"
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          if [ "${{ env.run-all }}" == "true" ]; then
            echo "Running all tests..."
            ginkgo -r
          else
            echo "Running filtered tests..."
            cd ./test/e2e && ginkgo -r --label-filter "${{ steps.get-labels.outputs.labels}}"
          fi

